Repository Joycehaoyuan/Group47-CITS5505, pull requests merged in 2025-05, with the labels that each got.

#22 Feature/share-add the html files about share functionality and write the README.md about our project details
  README.md
  app/static/css/styles.css
  app/templates/share_data.html
  app/templates/shared_with_me.html
Labels: documentation, Front-end

#19 feat(index): implement updated layout and new sections in index.html
  app/templates/index.html
Labels: Front-end

#25 Feature/chart meal js
  app/static/js/chart-config.js
  app/static/js/main.js
  app/static/js/meal-plan.js
Labels: enhancement, Design

#26 Feature/share: Implement Data Sharing Functionality
  app/forms.py
  app/models.py
  app/routes.py
  app/static/css/share_data.css
  app/static/js/share-data.js
  app/templates/share_data.html
  app/templates/shared_with_me.html
Labels: enhancement, Front-end, Design

#34 Feature/upload backend
  app/forms.py
  app/models.py
  app/routes.py
  app/templates/upload_data.html
Labels: backend

#36 Recipe Suggestion API Integration
  app/__init__.py
  app/config.py
  app/recipe_api.py
  app/static/js/meal-plan.js
  app/templates/meal_plan.html
  requirements.txt
Labels: enhancement, Design, backend

#45 Add meal plan utility functions and integrate with route handlers
  app/routes.py
  app/utils.py
Labels: documentation, enhancement, task, backend

#48 Enhance Registration Form Validation with Regex and Custom Messages #47
  app/forms.py
Labels: documentation, task, Security, backend, code-quality, UI

#46 Enhancement/unify upload tabs
  app/routes.py
  app/templates/base.html
  app/templates/upload_data.html
Labels: enhancement, help wanted, Design

#50 Implement Flask Application Factory Pattern and Enhanced Configuration
  app.py
  app/static/js/main.js
  app/static/js/share-data.js
  app/utils.py
  config.py
Labels: bug, enhancement, backend, code-quality

#54 Fix bugs in Share functionality
  app/templates/base.html
  app/templates/share_data.html
Labels: bug, enhancement, code-quality

#55 Debugging/frontend
  app/static/css/error.css
  app/static/css/login_reg.css
  app/static/css/meal_plan.css
  app/static/css/share_data.css
  app/static/css/upload.css
  app/static/js/meal-plan.js
  app/static/js/upload.js
  app/templates/csrf_error.html
  app/templates/index.html
  app/templates/login.html
  app/templates/meal_plan.html
  app/templates/register.html
  app/templates/upload_data.html
Labels: Front-end, java script

#59 Add new migration version file
  .gitignore
  migrations/README
  migrations/alembic.ini
  migrations/env.py
  migrations/script.py.mako
  migrations/versions/6c23174b5ed6_initial_migration.py
  migrations/versions/7c2a44556a19_add_recipe_enhancements.py
Labels: database

#61 test: add all unit and selenium test files
  app/__init__.py
  requirements.txt
  tests/__init__.py
  tests/conftest.py
  tests/selenium/__init__.py
  tests/selenium/test_auth.py
  tests/selenium/test_meal_plan.py
  tests/selenium/test_upload.py
  tests/test_config.py
  tests/unit/__init__.py
  tests/unit/test_forms.py
  tests/unit/test_models.py
  tests/unit/test_routes.py
  tests/unit/test_utils.py
Labels: enhancement, test

#62 Add unit tests for models: Recipe
  tests/unit/test_models.py
Labels: test

#67 update the readme about the page description and modify the js code to fix some small bugs.
  README.md
  app/static/js/delete-data.js
Labels: bug, enhancement, code-quality
